version: '3.8'

# ComfyUI & Stable Diffusion - Image Generation Stack
# Uses RTX 3090 (GPU 0) - plenty of VRAM for both Ollama and image generation
# Access ComfyUI at: http://ai-stack:7860
# Access SD-WebUI at: http://ai-stack:7861

services:
  # ComfyUI - Advanced node-based image generation
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "${COMFYUI_PORT:-7860}:18188"  # Direct access to ComfyUI (bypass auth portal)
    volumes:
      - comfyui_data:/workspace
      - ./comfyui/models:/workspace/models  # Share models
      - ./comfyui/custom_nodes:/workspace/custom_nodes
    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # RTX 3090 - Plenty of VRAM!
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - COMFYUI_FLAGS=--listen 0.0.0.0
      - WEB_ENABLE_AUTH=false  # Disable authentication portal
      - DIRECT_ADDRESS=100.119.32.64:7860  # Set proper access URL
      - DIRECT_ADDRESS_GET_WAN=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - ai-network

  # Stable Diffusion WebUI - User-friendly interface
  stable-diffusion-webui:
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-cuda
    container_name: sd-webui
    restart: unless-stopped
    ports:
      - "${SD_WEBUI_PORT:-7861}:17860"  # Direct access to WebUI (bypass auth portal)
    volumes:
      - sd_webui_data:/workspace
      - ./comfyui/models:/workspace/models  # Share models with ComfyUI
    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # RTX 3090 - Much faster and more VRAM!
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - COMMANDLINE_ARGS=--listen --xformers --api
      - WEBUI_LAUNCH_LIVE_OUTPUT=true
      - WEB_ENABLE_AUTH=false  # Disable authentication portal
      - DIRECT_ADDRESS=100.119.32.64:7861  # Set proper access URL
      - DIRECT_ADDRESS_GET_WAN=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - ai-network

volumes:
  comfyui_data:
    driver: local
  sd_webui_data:
    driver: local

networks:
  ai-network:
    external: true
    name: ai-stack_ai-network

