version: '3.8'

# ComfyUI & Stable Diffusion - Image Generation Stack
# Uses GTX 1050 Ti (GPU 1) for image generation
# Access ComfyUI at: http://ai-stack:7860
# Access SD-WebUI at: http://ai-stack:7861

services:
  # ComfyUI - Advanced node-based image generation
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "${COMFYUI_PORT:-7860}:7860"
    volumes:
      - comfyui_data:/workspace
      - ./comfyui/models:/workspace/models  # Share models
      - ./comfyui/custom_nodes:/workspace/custom_nodes
    environment:
      - NVIDIA_VISIBLE_DEVICES=1  # GTX 1050 Ti
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - COMFYUI_FLAGS=--listen 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    networks:
      - ai-network

  # Stable Diffusion WebUI - User-friendly interface
  stable-diffusion-webui:
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-cuda
    container_name: sd-webui
    restart: unless-stopped
    ports:
      - "${SD_WEBUI_PORT:-7861}:7860"
    volumes:
      - sd_webui_data:/workspace
      - ./comfyui/models:/workspace/models  # Share models with ComfyUI
    environment:
      - NVIDIA_VISIBLE_DEVICES=1  # GTX 1050 Ti
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - COMMANDLINE_ARGS=--listen --xformers --medvram --no-half-vae --api --opt-sdp-attention
      - WEBUI_LAUNCH_LIVE_OUTPUT=true
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    networks:
      - ai-network

volumes:
  comfyui_data:
    driver: local
  sd_webui_data:
    driver: local

networks:
  ai-network:
    external: true
    name: ai-stack_ai-network

