# SearXNG Configuration for AI Stack
use_default_settings: true

general:
  debug: false
  instance_name: "AI Stack Search"

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "e47b840e104a7198a1bde68031d4708b06585964ccd986479adfb321deda3d60"
  base_url: false
  image_proxy: true

ui:
  default_theme: simple
  default_locale: en

outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0

engines:
  - name: google
    engine: google
    shortcut: g
    
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    
  - name: github
    engine: github
    shortcut: gh
    
  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
